### ISSUE TITLE
Картинки к сообщениям об изменениях от Бота

### ISSUE THREAD

**Issue by llirrikk** [orioks-monitoring/bot#14]
## Дополнение к уведомлениям об изменениях в категориях **Оценки** и **Новости**
Подразумевается, что картинка дополнит сообщение от Бота, которой можно будет удобно поделиться с друзьями.

### Пример с разделом оценок

> 📗 **А/П.1** по «Электроника»
> Изменён балл за контрольное мероприятие:
> 0 —> 15 (из 20) (+ 15)
> 
> _Общая сумма баллов: 30 из 40_

![grade_example](https://user-images.githubusercontent.com/31863181/161613341-ca054a57-6cc9-4f24-9488-8954b265256b.jpg)

### Пример с разделом новостей

> 📰 **Выбор элективных и факультативных дисциплин на 1 семестр 2022-2023 уч.г.**
> 
> Опубликована новость, подробности по ссылке: https://orioks.miet.ru/main/view-news?id=474

![news_example](https://user-images.githubusercontent.com/31863181/161613345-537004e5-b781-43c5-8d97-c1a019afec1d.jpg)

## Готовые фоны для сообщений
_Спасибо, @marplyn_
- **Шрифт**: `PT Sans Caption Bold`
- **Размер**: верхний — `18 пт (24 px)`, нижний — `16 пт (22 px)` (либо -1 в каждом соответственно)
- **Цвет**: верхний — `#FFFFFF` `(255, 255, 255)`, нижний — `#C6F1FF` `(198, 241, 255)`
**QR для новостей**: цвет `#008CBA`, размер `160x160 px`

Фоны имеют разрешение `1500x750 px` и соотношение сторон `2:1`, поэтому есть возможность видеть картинку полностью, без необходимости её открытия на весь экран.

### Раздел оценок
Цвета эмодзи взяты из ОРИОКС.
- Если _«двойка»_: `current_grade` / `max_grade` < 50%
![grade_2_tag](https://user-images.githubusercontent.com/31863181/161612276-8de102bb-9230-41c0-aa24-cc49796d42b1.png)

- Если _«тройка»_: 50% <= `current_grade` / `max_grade` < 70%
![grade_3_tag](https://user-images.githubusercontent.com/31863181/161612289-4422c809-467f-4568-9364-0fb4e26edda6.png)

- Если _«»четвёрка»_: 70% <= `current_grade` / `max_grade` < 85%
![grade_4_tag](https://user-images.githubusercontent.com/31863181/161612291-d09aad4a-0318-4fa5-9a15-4984e7971268.png)

- Если _«пятёрка»_: 85% <= `current_grade` / `max_grade`
![grade_5_tag](https://user-images.githubusercontent.com/31863181/161612295-be6c52fb-0c12-4bb1-9409-a4b22bf3b99d.png)

### Раздел новостей
![news_tag](https://user-images.githubusercontent.com/31863181/161612310-7ce8acb3-c4e6-4754-9fdb-6a37734788e6.png)

**Comment by Whom-m0rty** [comment]
Всем привет. Учавствовать в разработке можно?)

**Comment by llirrikk** [comment]
Привет, конечно. Какие технологии предлагаешь использовать для этого issue? Ты из МИЭТ?

**Comment by Whom-m0rty** [comment]
Да, я из МИЭТа. Думаю, буду использовать Pillow для генерации картинок. На счет Qr ещё не гуглил. 

В каком формате возвращать картинки, сразу в байтах? Или путь?

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/161930949-7582714a-d1a6-40b3-bdce-c17814fc54bf.png)
Размеры шрифтов в Pillow не совпадают с размерами шрифтов в PhotoShop

``` font_upper = ImageFont.truetype('source/PTSansCaption-Bold.ttf', size=32) ```

Так же, мне необходимо узнать межстрочное расстояние, в примере я использовал 40 px.

**Comment by Whom-m0rty** [comment]
Так же, хотелось бы узнать, будет ли удобно отправлять в мою реализацию сразу готовые строки?

**Comment by llirrikk** [comment]
У варианта с Pillow есть некоторые проблемы:
1. Многострочный текст костыльными путями добавляется на картинку;
2. Если текст длинный (особенно актуально для категории с новостями), то опять же костыльными-непонятно какими способами его нужно правильно масштабировать, чтобы он не вылезал за края экрана;
3. При использовании pillow, он блокирует ход выполнения программы, потому что нет поддержки асинхронности. Но, думаю, это не критично, поскольку ОРИОКС еле дышит и без Бота. А если попытаться ускорить запросы, то ОРИОКС вовсе умрёт и не встанет никогда. Поэтому задержки скрипта идут нам на руку.

Я думаю ещё над вариантом подготовки шаблонов в html, css, чтобы можно было удобно поместить текст в html файлик, и чтобы он сам подогнался под нужные размеры (конечно, надо css написать правильно для этого). Затем нужно это всё конвертировать в картинку. В этом варианте намного больше возможностей и гибкости, хотя и первый, вероятно, подходит.

**Comment by marplyn** [comment]
> Размеры шрифтов в Pillow не совпадают с размерами шрифтов в PhotoShop
> 
> `font_upper = ImageFont.truetype('source/PTSansCaption-Bold.ttf', size=32)`

**Кегль**: верхний — `41 px`, нижний — `33 px` 
*(должно работать при длинном названии тоже)*

> Так же, мне необходимо узнать межстрочное расстояние, в примере я использовал 40 px.

**Интерлиньяж**: верхний — `45 px`, нижний — `40 px`

**Comment by llirrikk** [comment]
> В каком формате возвращать картинки, сразу в байтах? Или путь?

Думаю лучший вариант — это возвращать в байтах. Потому что в любом случае эта картинка нужна только для одноразовой отправки и нет необходимости её хранения на сервере.
Вероятно для отправки будет использовано это: https://docs.aiogram.dev/en/dev-3.x/api/upload_file.html#upload-from-buffer

**Comment by llirrikk** [comment]
> Так же, хотелось бы узнать, будет ли удобно отправлять в мою реализацию сразу готовые строки?

Так как особо никакой сложной разметки на картинках пока не планируется делать, передавать лучше сразу готовую строку, а не словарь

**Comment by marplyn** [comment]
> Размеры шрифтов в Pillow не совпадают с размерами шрифтов в PhotoShop
> 
> `font_upper = ImageFont.truetype('source/PTSansCaption-Bold.ttf', size=32)`

**Кегль**: верхний — `75 px`, нижний — `66 px` 

> Так же, мне необходимо узнать межстрочное расстояние, в примере я использовал 40 px.

**Интерлиньяж**: верхний — `80 px`, нижний — `70 px`

Должно работать и при длинных названиях с переносами, в разных вариациях с ориентацией по центру изображения, с минимальными вертикальными полями около `230 px`, горизонтальными около `150 px`.

Конечно, размеры даны в базовом соотношении, их можно изменить исходя из текстового содержания.

**Comment by Whom-m0rty** [comment]
Посмотрел я на это все, принял решение переписать с Pillow на HTML

**Comment by Whom-m0rty** [comment]
![image](https://user-images.githubusercontent.com/56591372/161964048-f2057a7a-dea0-4800-b5a2-349eaed5b545.png)
В размеры снова не получилось попасть, я очень плох в html... Надеюсь, это не проблема. Сейчас напишу обертку этого веселья.

Кстати время исполнения достаточно долгое, потому что HTML рендерится в картинку. Есть другой способ скормить HTML телеграму?

**Comment by llirrikk** [comment]
Да размеры необязательно pixel perfect делать. На глаз можно :)
Время исполнения - это действительно проблема, но зато появляется больше возможностей. Надо как-то выбрать, что важнее в данной задаче: время исполнения или гибкость настройки.
Если тебе как-то удастся поработить многострочные/длинные тексты с Pillow, то можно и не использовать идею с html шаблонами. Других способов преобразовать текст в картинку я не знаю.
Короче, четкого ТЗ от меня нет, делай как считаешь нужным, а я потом подстрою

> скормить HTML телеграму

так это же надо в картинку скармливать, а в телеграм. Если ты про https://instantview.telegram.org/, то это же для статей в первую очередь

**Comment by Whom-m0rty** [comment]
После гнева, торга, депрессии, бутылки бренди и наконец смирения я решил сделать перенос текста с помощью Pillow. 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/56591372/162023235-e0b5d78f-5701-4be9-a8e1-5b00d7dc3d8b.png">

Вопрос таков:

`Центровать строку после переноса? `

**Comment by marplyn** [comment]
> Вопрос таков:
> 
> `Центровать строку после переноса?`

Да! :)

**Comment by llirrikk** [comment]
> После гнева, торга, депрессии, бутылки бренди и наконец смирения

это ты еще сервер ОРИОКС не ложил двумя запросами в одну секунду

**Comment by marplyn** [comment]
true story

**Comment by llirrikk** [comment]
> Вопрос таков:
> 
> `Центровать строку после переноса? `

у `drawer = ImageDraw.Draw(image)` в методе `multiline_text` есть параметр `align='center'`, который делает это автоматически

**Comment by Whom-m0rty** [comment]
Вот что у меня получилось:

![1](https://user-images.githubusercontent.com/56591372/162025881-4b650d45-9406-491d-90dd-c664f2bbd659.png)

Работает быстрее чем рендер HTML, хоть я и не засекал.

**Comment by Whom-m0rty** [comment]
Переходить к рефактору? Или что-то поправить нужно?

**Comment by llirrikk** [comment]
Выглядит красиво, но
1. Когда + 15 при 20 макс., это должно входить в зону "четверки", потому что 15/20 = 0,75 < 0,85. Или если ты принимаешь в функцию текст и фон, то вопросов нет: это уже моя будет задача передавать правильный фон;
2. Шрифты заголовка и текста под заголовком нужно сделать немного больше

Сделай, пожалуйста, второй пункт, затем пришли результат, и тогда наверное можно будет переходить к рефакторингу

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162029064-9f577c54-9440-425c-8519-9684d4bcd1c8.png)

`Когда + 15 при 20 макс., это должно входить в зону "четверки", потому что 15/20 = 0,75 < 0,85. Или если ты принимаешь в функцию текст и фон, то вопросов нет: это уже моя будет задача передавать правильный фон;`

- класс сам подбирает картинку по параметрам

`Шрифты заголовка и текста под заголовком нужно сделать немного больше`

- Сделано

**Comment by Whom-m0rty** [comment]
а ой, заметил баг после рефакторинга, сча исправлю

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162029651-02b574aa-693d-45a5-be69-247fcb75eb43.png)

**Comment by Whom-m0rty** [comment]
`current_grade=15, max_grade=20`

![1](https://user-images.githubusercontent.com/56591372/162029817-23834d3b-7396-4608-9d81-b7561c5cc5e3.png)

**Comment by llirrikk** [comment]
Щас @marplyn напишет пожелания по-мелочи и можешь рефакторить. Спасибо

**Comment by marplyn** [comment]
Хорошо выходит, но 
1. Шрифт можно сделать ещё больше
2. Вертикальные поля сделать шире

Референс с длинным названием:
![710C4297-BA04-4F68-BE71-0F6BE8EF9596](https://user-images.githubusercontent.com/88846445/162030952-ffc5128c-76bb-40c6-877a-621d442d11cf.jpeg)

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162031588-db9cd507-c82a-4d9c-8374-cf93c29c3300.png)

или 

![1](https://user-images.githubusercontent.com/56591372/162031692-8b6f756a-db3d-4797-8444-75a0c01da2c1.png)

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162032994-06f81274-1b64-4b45-9f93-f7919433095d.png)

Так?

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162033401-6521ad1a-6c23-40d7-8bcb-45278183329c.png)

Увеличил размер шрифта

**Comment by Whom-m0rty** [comment]
Так отработал текст из референса 

![1](https://user-images.githubusercontent.com/56591372/162033737-8241dc15-8866-4fc3-826d-b5876629396e.png)

**Comment by Whom-m0rty** [comment]
![1](https://user-images.githubusercontent.com/56591372/162151202-7c255655-3cca-4b65-aea5-935ab0c14c6c.png)


![1](https://user-images.githubusercontent.com/56591372/162151356-a315e525-8ea0-4037-8e93-c06d2cd7c8f0.png)

Ну как-то так

**Comment by marplyn** [comment]
Всё нравится, замечаний нет, отлично сделал :)

**Comment by Whom-m0rty** [comment]
https://github.com/orioks-monitoring/bot/pull/16
