### ISSUE TITLE
Логаут неактивных (удаленных) аккаунтов

### ISSUE THREAD

**Issue by marplyn** [orioks-monitoring/bot#32]
Необходимо делать логаут отчисленных/закончивших обучение пользователей, чтобы снизить количество запросов и выправить статистику сколько реально действующих студентов из авторизованных в боте. 

Например, если подряд происходит n ошибок парсинга, то делать логаут и отсылать "Не удалось получить информацию, необходима повторная авторизация". Кто отчислился/закончил проигнорят, а кому надо, то авторизуются еще раз (может есть более элегантное решение?)

**Comment by llirrikk** [comment]
Нужно ли заботиться, чтобы сообщение "Не удалось получить информацию, необходима повторная авторизация" не приходило в 3 утра например?

**Comment by marplyn** [comment]
По факту, скорее всего, это оповещение получит тот, кто уже не студент. Но по-хорошему стоит предусмотреть время отправки

**Comment by llirrikk** [comment]
Еще могут получить люди, у которых баннер вылез, требующий обязательного клика

**Comment by marplyn** [comment]
Если мы не можем дифференцировать пользователей, которых больше нет в системе, и пользователей с баннером, то тогда конечно нужно сделать адекватное время отправки сообщения

**Comment by llirrikk** [comment]
"адекватное время отправки сообщения" было принято решение не делать
