### ISSUE TITLE
Сделать парсинг расписания

### ISSUE THREAD

**Issue by Whom-m0rty** [orioks-monitoring/bot#38]
Появилась идея сделать отображение расписания по кнопке в боте.

Например:

(На момент 10:35)

Расписание на сегодня:

1. Электротехника 9:00-10:30 (А.С. Пушкин)
<- Вы тут.
2. Механика 10:40 - 12:10 (А.С. Пушкин)

Или 

(На момент 10:50)
Расписание на сегодня:

1. Электротехника 9:00-10:30 (А.С. Пушкин)
2. Механика 10:40 - 12:10 (А.С. Пушкин) <- Вы тут.

Но существуют проблемы:
1. У нас в группе числитель и два расписания для знаменателя.
2. Как понимать когда большая перемена? 
3. Откуда брать актуальное расписание? (Вроде как https://miet.ru/schedule но актуальное ли там?)

Если я буду хранить расписание в json, а бот будет его оттуда забирать, хороший ли это подход?

Планирую написать таску для celery crontab для актуализации расписания.

**Comment by Whom-m0rty** [comment]
Ошибся, 

(На момент 10:50)
Расписание на сегодня:

1. Электротехника 9:00-10:30 (А.С. Пушкин)
2. Механика 10:40 - 12:10 (А.С. Пушкин) <- Вы тут.

**Comment by marplyn** [comment]
Обсуждали в #30 

Повтори там, пожалуйста
